name = input('Enter Name ✌')
dob = input('Enter Date of Birth 🎂')
city = input('Enter City')
college = input('Enter College')
fav_color = input('Enter Favorite Color')
fav_food = input('Enter Favorite Food')
fav_animal = input('Enter Favorite Animal')
fav_movie = input('Enter Favorite Movie')
fav_song = input('Enter Favorite Song')
print(name, dob, city, college, fav_color, fav_food, fav_animal, fav_movie, fav_song)